# Site settings
title: Reverse Jekyll
email: dummy-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A demo site to be used to walkthrough developers reverse engineer a
  static site to Jekyll Structure.
baseurl: ""
url: ""

# Build settings
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
